### ISSUE TITLE
Platforms

### ISSUE THREAD

**Issue by PolBaladas** [fossasia/event-collect#1]
Hi, I think we should develop a scraper (script) for each platform --> Different Files. 
And store them in a "Platforms" folder.

**Comment by SaptakS** [comment]
@PolBaladas do you mean like for example scraping google sheets and other forms of data store for getting the various information? I think that is a good idea. We can do that for CFPs maybe. And then import in eventyay.com. @niranjan94 @mariobehling what do you think?

**Comment by PolBaladas** [comment]
Once scraped, we've got two options:
1.  Each script should directly create all result Files (JSONs, Img Folder)
2.  Each script should save results in a single JSON file and then have another script parse that and create and download images.

**Comment by PolBaladas** [comment]
Hi @SaptakS, I was thinking about directly scraping info from the event-lsiting site.

**Comment by PolBaladas** [comment]
Found this: http://www.menifeebuzz.com/bizz-buzz/item/1316-17-free-event-listing-websites

**Comment by mariobehling** [comment]
@PolBaladas Y

> Each script should directly create all result Files (JSONs, Img Folder)

This would be straight forward and great, if it could work out like that.

> CFPs

Means Call for Papers. Let's make this a later task and think this through first.

**Comment by PolBaladas** [comment]
Hi @mariobehling I think that it can definitely work out like that. What i don't see yet is the kind of platforms we're talking about: meetup-like or like the ones in the link? Maybe start with [Eventbrite](https://www.eventbrite.com/)?

The best would be to start scraping a single event (by event URL or ID of each platform). As this is intended for a search engine, we will have to work out the "search page" scraping (to get the events) later, right? 

I can definitely see a lot of tasks/issues coming from this idea, to add more platforms.

**Comment by mariobehling** [comment]
@PolBaladas We need an automated approach. @jig08 had started something with loklak. 

Please check, if that can get you started: https://github.com/loklak/loklak_server/blob/development/docs/parsers.md#event-brite-crawler

**Comment by mariobehling** [comment]
An idea would be to run a loklak instance to scrape event websites. The process would be as follows:
* Someone make a search on eventyay.com
* The search term is also made to the loklak instance. This triggers a search on an event site from the loklak instance.
* The search results are scraped by loklak.

All this is not implemented yet. What are the steps to get this going?

Could we start with a simple scraper of the search results of event services, that we can then integrate into loklak?

**Comment by PolBaladas** [comment]
I see @mariobehling , as we have already scraped Eventbrite and Meetup, we need a search result scraper of these two platforms.
query --> scraper --> event links
Then, we pass the scraped event links to loklak's API and save the JSON? We can start with that, no problem. 
event links --> loklak API --> JSON

**Comment by PolBaladas** [comment]
Hi there! EventBrite platform Working @mariobehling @jig08 
At the moment, scraping only first page of results. Scraping all reult pages can be done if needed.

Maybe each platform should become a GCI task?

**Comment by jig08** [comment]
>Hi there! EventBrite platform Working @mariobehling @jig08

@PolBaladas Yes :)

>Maybe each platform should become a GCI task?
@mariobehling I had proposed this in the spreadsheet of tasks we maintain.

**Comment by mariobehling** [comment]
> EventBrite platform Working 

Working in what sense? Where is it on http://loklak.org ?

**Comment by jig08** [comment]
@mariobehling
I guess @PolBaladas meant the scraping works in a crude sense.
Sample link: http://loklak.org/api/eventbritecrawler.json?url=https://www.eventbrite.fr/e/billets-europeade-2016-concert-de-musique-vocale-25592599153

**Comment by mariobehling** [comment]
@jig08 Ok. How can your example be called from a loklak UI? How can search terms be entered and give out a list of events?

**Comment by PolBaladas** [comment]
Yes and No, @mariobehling  I submited a PR with a script that works in the following manner:

`python scrape_eventbrite.py [SEARCH QUERY]`

**Comment by ashwini0529** [comment]
If there's any work left, please let me know! :)

**Comment by enigmaeth** [comment]
How can we use the loklak instance to get the images and other files? ( Refer Issue #15 ) 
Do we need to add image and media files scraping into the existing platforms? 
Also, if we are downloading the image/media files while importing( these might be big in size), it will cause overhead. One solution is to scrape image links and embed them on request and maybe download them later in a background process. 

@mariobehling  @jig08 @PolBaladas  What do you say?

**Comment by mariobehling** [comment]
@enigmaeth All data should be on our platform. But, actually as there are so many bugs on the open event server this project should be done later (we need a more stable project first) and we are all busy with the bugs of the system now.

**Comment by mariobehling** [comment]
I am closing this issue now as results in a rather broad discussion and many different points that come up. We can come back to this in a more narrow discussion, e.g. we should start with one platform first and get experience before we discuss all possible use cases, options and platforms and have a super long discussion. So, let's go step by step instead of trying to solve all at once. We have open issues in the server platform about elastic search. So, if you want to get into the search topic, I suggest, please start there. Thank you.

**Comment by enigmaeth** [comment]
Yes. I aim to work on the import system as my GSoC project. I have planned to make atleast one platform working perfectly and then proceeding to the others because then it would also be easy. Hope we get the server system stable first. I will look through the elastic search issues.
