### ISSUE TITLE
Collect event details from Google Spreadsheet

### ISSUE THREAD

**Issue by SaptakS** [fossasia/event-collect#10]
Many times, the event or session information are stored in google spreadsheets. One can write a scrapper to scrap all such events from the google spreadsheet.

**Comment by mariobehling** [comment]
@SaptakS Correct. That is what we did for previous events. How does this fit in with the event collector?

**Comment by SaptakS** [comment]
@mariobehling this is not exactly information for the entire event, but we can make a scraper for collecting session, speaker, ticket, etc. informations for a particular event provided the links. I thought it would be appropriate to have that scrapper as a part of event-collect since it is being used to collect information about a particular event.

**Comment by mariobehling** [comment]
@SaptakS Yes, but for the event collector we are looking at a more generic solution. Using spreadsheets, each one of them would be mostly have a different structure. So, I think for this module it would be out of scope.

**Comment by SaptakS** [comment]
@mariobehling yes, if same structure is not followed then it won't be possible. I mean we can try to assume similar columns but that's it.

**Comment by mariobehling** [comment]
@SaptakS Let's get back to this later then and close this for now. Thank you.
