### ISSUE TITLE
Are samples required in the main repository ?

### ISSUE THREAD

**Issue by niranjan94** [fossasia/event-collect#14]
@mariobehling do we need to have samples in the repository ? 

For example these,

1. https://github.com/oanarosca/event-collect/tree/bb937822a6a4791e539913603ad065b8c65cb8ed/platforms/movies
2. https://github.com/fossasia/event-collect/tree/master/examples/eventbrite
3. https://github.com/fossasia/event-collect/tree/master/platforms/fossasia%202016

They take up space but server no purpose other than to check if the scrapper output is correct or not.

Instead of adding it to the repo, any PR that is submitting a new scrapper can attach zipped samples to the PR itself. So that we'll still be able to review and test the output and at the same time it would not clutter the repo with unnecessary data.

**Comment by mariobehling** [comment]
> Instead of adding it to the repo, any PR that is submitting a new scrapper can attach zipped samples to the PR itself. 

Sounds better. Please proceed. Thank you.

**Comment by niranjan94** [comment]
@mariobehling done. Repo has been cleaned up. The samples have been zipped and attached to their respective PRs.
