### ISSUE TITLE
Scrape Images and other files from eventbrite

### ISSUE THREAD

**Issue by enigmaeth** [fossasia/event-collect#15]
Currently, the images and other media files are not being exported into the folder of an event concerned. 
The event ZIP from Open-Event has the following directory structure for media files:
```sh
   - images\
       - sponsors\
       - speakers\
       - logo.ext
   - videos\
   - audios\
   - slides\
```
Implement this feature to make the set of JSON exactly like that of the Open Event Server API.

**Comment by enigmaeth** [comment]
@PolBaladas How can we scrape images from event brite? What changes are to be made in the current state of the scraper?

**Comment by iharshit009** [comment]
Is this issue resolved or we have to work on it??

**Comment by iharshit009** [comment]
hey, can I work on this Issue?

**Comment by b-thebest** [comment]
Hello, I am experiences well in scraping, Can you assign this issue to me please?

**Comment by enigmaeth** [comment]
@b-thebest sorry, I no longer work on this project. You should contact the project owners who might be able to help with the current state of the project. (For reference, you can look at the current active contributors [here](https://github.com/fossasia/event-collect/graphs/contributors).) 

Best!
