### ISSUE TITLE
Scraping/APIs

### ISSUE THREAD

**Issue by PolBaladas** [fossasia/event-collect#2]
While Scraping is a great method to build this tool, Should we consider the option of using platforms APIs?

**Comment by mariobehling** [comment]
@PolBaladas Platform APIs would increase our dependency on the API itself and require registrations etc. Some services use internal JSON files ("internal APIs"). If we could identify them in any of the services, this would be great though. Otherwise let's go with scraping for now. Cheers.

**Comment by PolBaladas** [comment]
Alright!
